### ISSUE TITLE
Gamify the thing

### ISSUE THREAD

**Issue by d33tah** [omnilingo/omnilingo#2]

**Comment by ftyers** [comment]
Ideas for points/metrics:
* Time taken to answer
* How many times audio is played
* Number of correct answers per N

**Comment by d33tah** [comment]
I just had that thought after watching my Anki statistics: if you track everything and use something as a habit, you quickly accumulate a crazy amount of information. We definitely shouldn't store it on our servers (or at least not in a way that's accessible), but having a way to let user have some insight into how they use our app would be awesome.

**Comment by ftyers** [comment]
I've implemented a system where you start at level 1 and the system tracks how long it takes you to answer the questions with randomly selected tasks. If you beat the audio time, then it moves you up a level, otherwise you stay at the same level and get the same questions but with different tasks. This seems like a reasonable approach to start with. The score ends up being the ratio of your speed at answering to the length of the audio.
