### ISSUE TITLE
Work out a better way to serve the mp3s

### ISSUE THREAD

**Issue by ftyers** [omnilingo/omnilingo#20]
Ideally it should be possible to serve them outside of the current directory.

**Comment by d33tah** [comment]
@ftyers to solve this specific problem, you should be able to use symbolic links.

I agree that better way of serving mp3s would definitely be nice to have. IMHO we should be serving static data from a separate domain, so that once we deploy the project, scaling would be easier. Not exactly sure how to do that yet.

**Comment by d33tah** [comment]
BTW, we really need a place to host a demo. Ideally along with one where we could re-host the Common Voice data.

**Comment by ftyers** [comment]
I think we can close this one now too.
